name = "plm-under_construction"
compatibility_date = "2024-10-03"
pages_build_output_dir="./dist"
# This is a static site configuration for Cloudflare Pages

# For deployment, use: npx wrangler pages deploy dist --project-name=plm-under_construction
